Feature/storage s3
greenpress/assets-service pull request #17
Opened 2021-02-09 18:33 UTC by OmerGronich

2021-02-09 19:23 UTC, drorrose commented
@davidmeirlevy @OmerGronich 
On my computer couldn't run the service due to error (not finding aws-sdk, even though locally installed and in package.json). Does it reproduce on any of your computers?

2021-02-09 19:24 UTC, OmerGronich commented
@davidmeirlevy @drorrose @or-yam 
Renaming asssets is still WIP.

2021-02-09 19:34 UTC, OmerGronich commented
@davidmeirlevy  
in gcs services, when you load files you return the type property in the return value. 
gcs has the metadata.kind built in to the api but could not find a way to do this with s3.

`
async function loadFiles(storage, identifier = '/') {
  const gcs = new Gcs(storage)
  const fullPath = path.join(storage.metadata.basePath || '/', identifier)

  let list
  try {
    await gcs.ready
    list = await gcs.list(fullPath)
  } catch (e) {
    throw new Error(e.message || 'failed to get list of assets from: ' + fullPath)
  } finally {
    // run on background
    // TODO: reuse storage connection
    gcs.destroy()
  }

  return list.map((asset) => {
    const fileIdentifier = path.join(identifier, asset.metadata.name)

    return {
      name: asset.metadata.name,
      identifier: fileIdentifier,
      updated: asset.metadata.updated,
      **type: getAssetType(asset.metadata)**,
      publicUrl: joinUrl(storage.metadata.publicUrl, fileIdentifier)
    }
  })
}
`

2021-02-10 08:34 UTC, davidmeirlevy commented
@OmerGronich rach provider use a different approach to distinguish the file types, but as an assets-service, we should at least tell the user is this is an image, a folder, or another "asset".

2021-02-10 09:06 UTC, OmerGronich commented
> @OmerGronich rach provider use a different approach to distinguish the file types, but as an assets-service, we should at least tell the user is this is an image, a folder, or another "asset".

Got it 👍
I will figure it out.

2021-02-17 19:40 UTC, davidmeirlevy requested changes

2021-02-17 19:40 UTC, davidmeirlevy commented on server/models/s3.js
> +        AWS.config.setPromisesDependency();
This service is stateless and can run multiple times.. maybe this line should run only once?

2021-02-17 19:40 UTC, davidmeirlevy commented on server/models/s3.js
> +
Should destroy the this._client connection.

2021-02-19 17:11 UTC, OmerGronich commented on server/models/s3.js
> +        AWS.config.setPromisesDependency();
👍 no problem

moved outside of class -> [commit 277cb0895d8c838429c6a97533fbbb663b723c0c](https://github.com/greenpress/assets-service/pull/17/commits/277cb0895d8c838429c6a97533fbbb663b723c0c)

2021-02-20 01:01 UTC, OmerGronich commented on server/models/s3.js
> +
What does destroying the connection mean? 

All this._client requests are stateless, I'm pretty sure there is no continuous connection to S3. 
Can I delete this function?

2021-02-21 19:26 UTC, davidmeirlevy commented on server/models/s3.js
> +      return [...files, ...folders];
it's common to put folders first.

2021-02-21 19:27 UTC, davidmeirlevy commented on server/models/s3.js
> +      const files = await Promise.all(listedObjects.Contents.map(async content => {
Is there no faster way to load basic data for the files?
there are a lot of requests here.

maybe the next phase is to start with the caching mechanism here.

2021-02-21 19:29 UTC, davidmeirlevy commented on server/models/s3.js
> +      listedObjects.Contents.forEach(({ Key }) => {
why not to use map, like:
```
      const deleteParams = {
        Bucket: this.bucket.name,
        Delete: { Objects: listedObjects.Contents.map({Key} => ({Key})) }
      };
```

2021-02-21 19:30 UTC, davidmeirlevy commented on server/models/s3.js
> +      if (listedObjects.IsTruncated) await this.remove(file);
this looks a bit recursive. why is that?

2021-02-21 19:31 UTC, davidmeirlevy commented on server/routes/assets.js
> +function empty(_, res) {
you can remove this function we don't use it anymore.

2021-02-21 19:34 UTC, davidmeirlevy reviewed
minor changes left. this can be approved, but it can be even better with those changes. :)

2021-02-26 12:32 UTC, OmerGronich commented on server/models/s3.js
> +      return [...files, ...folders];
done

2021-02-26 12:46 UTC, OmerGronich commented on server/models/s3.js
> +      const files = await Promise.all(listedObjects.Contents.map(async content => {
No problem! The code is no longer making the extra request to s3 to get the object metadata. Now deriving the asset type  with our getAssetType function.

2021-02-26 16:25 UTC, OmerGronich commented on server/models/s3.js
> +      listedObjects.Contents.forEach(({ Key }) => {
Cool :) 
Refactored👍

2021-02-26 16:26 UTC, OmerGronich commented on server/routes/assets.js
> +function empty(_, res) {
done

2021-02-26 16:41 UTC, OmerGronich commented on server/models/s3.js
> +      if (listedObjects.IsTruncated) await this.remove(file);
the isTruncated boolean is s3's pagination flag. True = there are still assets left to retrieve

2021-02-26 17:53 UTC, davidmeirlevy approved these changes

2021-02-26 17:55 UTC, merged