feature/s3-renaming
greenpress/assets-service pull request #22
Opened 2021-02-27 01:23 UTC by OmerGronich

finished rename in s3
fixed "/" folder bug

2021-02-28 07:03 UTC, davidmeirlevy approved these changes

2021-03-02 19:34 UTC, drorrose requested changes
Such minor changes..The rest of the code looks great!

2021-03-02 19:34 UTC, drorrose commented on server/services/gcs.js
> +const { generateIdentifier } = require("./identifier");
change double quotes to single quotes, just to use the same format as the rest of the code

2021-03-02 19:34 UTC, drorrose commented on server/services/s3.js
> +const { generateIdentifier } = require("./identifier");
same comment about quotes, also should be changed in lines 1 and 5

2021-03-02 19:39 UTC, OmerGronich commented on server/services/gcs.js
> +const { generateIdentifier } = require("./identifier");
done

2021-03-02 19:39 UTC, OmerGronich commented on server/services/s3.js
> +const { generateIdentifier } = require("./identifier");
done

2021-03-02 19:41 UTC, drorrose approved these changes

2021-03-02 19:51 UTC, merged